[Interface]
PrivateKey = AOdAIGNxtvZvGymMT/Jfr5pg0io7Z1brFL585IJQzlU=
Address = 10.8.0.11/24
MTU = 1280

[Peer]
PublicKey = s+gyopeuQf3Rr/bCtpdEH9qXu+FKrd9ePPcySzrbKRg=
AllowedIPs = 10.8.0.0/24, 192.168.1.108/32, 10.0.0.0/24
Endpoint = 46.225.8.20:51820
PersistentKeepalive = 25
